server:
  port: 8088
spring:
  datasource:
    drivername: dm.jdbc.driver.DmDriver
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://10.0.7.62:5237/DMSERVER?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8_general_ci&allowMultiQueries=true
    username: SYSDBA
    password: SYSDBA

    druid:
      test-while-idle: true
      validation-query: SELECT 1

kingbase:
  url: jdbc:kingbase8://10.0.7.62:54321/TEST
  username: SYSTEM
  password: kingbase
  drivername: com.kingbase8.Driver